version: "2.4"
services:

  second:
    build:
      context: .
    image: second-pytorch:v1.5
    container_name: second
    volumes:
      - .:/root/second.pytorch
      - /mnt/smb/kitti/training/hybrid_v4:/root/data/kitti/training
      - /mnt/smb/kitti/testing/kitti:/root/data/kitti/testing
      - /mnt/smb/kitti/model:/root/model
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
