version: "2.4"

services:
  second:
    build:
      context: .
    image: second-pytorch:v1.5
    container_name: second
    volumes:
      - ${HOME}/.Xauthority:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/second.pytorch
      - /media/david/kitti/lgsvl-10000:/root/data
      - /media/david/kitti/second/kitti/testing:/root/data/kitti/testing
      - ${HOME}/pretrained_models_v1.5:/root/model
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIBOVERLAY_SCROLLBAR=0
      - GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-2.0/gtkrc
      - GTK_THEME=Adwaita
      - XAUTHORITY=/tmp/.Xauthority
    runtime: nvidia
    network_mode: host
    init: true
    privileged: true
